plugin: openstack.cloud.openstack

groups:
  staging: "'env=staging' in (openstack.tags|list)"
  production: "'env=production' in (openstack.tags|list)"

keyed_groups:
  - key: openstack.tags
    prefix: tags

cache: yes
cache_plugin: ansible.builtin.jsonfile
cache_timeout: 3600
cache_connection: dynamic_inventory
cache_prefix: os_
